#!/bin/bash

# Save the C file name in the variable $CFILE
CFILE="main.c"

# Compile the C file and create the executable
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 "$CFILE" -o cisfun

# Check if compilation was successful
if [ $? -eq 0 ]; then
    echo "Compilation successful. Executable created: cisfun"
else
    echo "Compilation failed"
fi
